license="MIT License"
modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory
issueTrackerURL="https://github.com/CodenameRevy/AdditionalBarsBOP/issues" #optional

[[mods]] #mandatory
modId="additionalbarsbop" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Additional Bars (Biomes o' Plenty addon)" #mandatory
displayURL="gamma1772.github.io" #optional
logoFile="logo.png" #optional
credits='''Gamma1772 (Mod Developer), ruchom4u (Spanish Translations), fantasyair18 (Chinese Traditional (Taiwan) Translations), TheDirectorX, BardinTheDwarf (Russian Translations), Zijuna (German Translations), justmonika (Simple Chinese Translations), mindy15963 (Korean Translations), WadeMason''' #optional
authors="Gamma1772" #optional
description='''Support for Biomes O Plenty wood types for Additional Bars'''

[[dependencies.additionalbarsbop]] #optional
    modId="additionalbars" #mandatory
    mandatory=true #mandatory
    versionRange="[3,)" #mandatory
    ordering="AFTER"
    side="BOTH"

[[dependencies.additionalbarsbop]] #optional
    modId="biomesoplenty" #mandatory
    mandatory=false #mandatory
    versionRange="[1,)" #mandatory
    ordering="AFTER"
    side="BOTH"
